//! Live test: write content to a deep, not-yet-existing remote path (must
//! mkdir -p), then read it back and verify.
//! `cargo run --example write_read -- liliang@192.168.123.214 ...`

use dispatch::{Config, Dispatch};

#[tokio::main]
async fn main() -> dispatch::Result<()> {
    let hosts: Vec<String> = std::env::args().skip(1).collect();
    let client = Dispatch::new(Config::default())?;

    // A nested directory that does NOT exist yet -> write must create it.
    let dest = "/tmp/dispatch-rs-test/a/b/c/config.toml";
    let content = b"# generated by dispatch-rs\nkey = \"value\"\n";

    // clean any prior run
    let _ = client
        .exec(hosts.clone(), "rm -rf /tmp/dispatch-rs-test")
        .run()
        .await?;

    println!("== write to {dest} (nested, dir absent) ==");
    let w = client
        .write(hosts.clone(), content.to_vec(), dest)
        .mode(0o600)
        .run()
        .await?;
    for (h, r) in &w.hosts {
        println!("  [{h}] ok={} {:?}", r.success, r.error);
    }
    println!("write all_success = {}", w.all_success());

    println!("== read it back ==");
    let r = client.read(hosts, dest).run().await?;
    for (h, hr) in &r.hosts {
        if hr.success {
            let same = hr.content == content;
            println!(
                "  [{h}] {} bytes, matches={}\n    {}",
                hr.content.len(),
                same,
                String::from_utf8_lossy(&hr.content).trim()
            );
        } else {
            println!("  [{h}] FAIL {:?}", hr.error);
        }
    }
    println!("read all_success = {}", r.all_success());
    Ok(())
}
